name: Update .env.local

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        description: 'Deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - 'production'
          - 'staging'
          - 'secondstaging'

jobs:
  update-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          ENVIRONMENT=${{ github.event.inputs['deploy-environment'] }}
          UPPER_ENVIRONMENT=$(echo $ENVIRONMENT | tr '[:lower:]' '[:upper:]')
          GMAP_KEY_NAME="NEXT_PUBLIC_GMAP_KEY_${UPPER_ENVIRONMENT}"
          GMAP_KEY_VALUE="${{ secrets[NEXT_PUBLIC_GMAP_KEY_PRODUCTION] }}"
          
          if [ "$ENVIRONMENT" == "staging" ]; then
            GMAP_KEY_VALUE="${{ secrets.NEXT_PUBLIC_GMAP_KEY_STAGING }}"
          elif [ "$ENVIRONMENT" == "secondstaging" ]; then
            GMAP_KEY_VALUE="${{ secrets.NEXT_PUBLIC_GMAP_KEY_SECONDSTAGING }}"
          fi
          
          echo "NEXT_PUBLIC_ENV=\"$ENVIRONMENT\"" > .env.local
          echo "NEXT_PUBLIC_GMAP_KEY=$GMAP_KEY_VALUE" >> .env.local

      - name: Display .env.local
        run: cat .env.local
