name: Update .env.local

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        description: 'Deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - 'production'
          - 'staging'
          - 'secondstaging'

jobs:
  update-env:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          ENVIRONMENT=${{ github.event.inputs['deploy-environment'] }}
          
          if [ "$ENVIRONMENT" == "production" ]; then
            echo "NEXT_PUBLIC_ENV=\"$ENVIRONMENT\"" > .env.local
            echo "NEXT_PUBLIC_GMAP_KEY=${{ secrets.NEXT_PUBLIC_GMAP_KEY_PRODUCTION }}" >> .env.local
          elif [ "$ENVIRONMENT" == "staging" ]; then
            echo "NEXT_PUBLIC_ENV=\"$ENVIRONMENT\"" > .env.local
            echo "NEXT_PUBLIC_GMAP_KEY=${{ secrets.NEXT_PUBLIC_GMAP_KEY_STAGING }}" >> .env.local
          elif [ "$ENVIRONMENT" == "secondstaging" ]; then
            echo "NEXT_PUBLIC_ENV=\"$ENVIRONMENT\"" > .env.local
            echo "NEXT_PUBLIC_GMAP_KEY=${{ secrets.NEXT_PUBLIC_GMAP_KEY_SECONDSTAGING }}" >> .env.local
          else
            echo "Error: Invalid environment specified"
            exit 1
          fi

      - name: Display .env.local
        run: cat .env.local
