name: Automate Comments 

on:
  workflow_call:
    inputs:
      days:
        required: true
        type: string
        
      comment:
        required: true
        type: string
        
      mention:       
        required: true
        type: string

jobs:
  list-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List and update issues
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Step 1: Checking out repository');

            // Define options for listing issues
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            console.log('Step 2: Retrieving issues');
            // Retrieve all open issues for the repository
            const issues = await github.paginate(opts);

            console.log('Step 3: Processing issues');
            // Loop through each issue
            for (let i = 0; i < issues.length; i++) {
              const issue = issues[i];
              console.log('Processing issue:', issue.number);

              // Get the last updated timestamp of the issue and the current timestamp
              const issueLastUpdated = new Date(issue.updated_at);
              const currentDate = new Date();

              // Calculate the time difference in milliseconds between the last update and the current time
              const timeDifference = currentDate - issueLastUpdated;
              const minutesInMilliseconds = parseInt('{{ inputs.days }}') * 60 * 1000; // Use the input value here

              // Check if the issue hasn't been updated in the specified number of minutes
              if (timeDifference >= minutesInMilliseconds) {
                console.log('Issue ' + issue.number + ' needs an update');

                // Create the comment text with mention
                const mention = '{{ inputs.mention }}';
                let mentionText = '';

                if (mention === 'owner') {
                  mentionText = `@${issue.user.login}`;
                } else if (mention === 'assignees') {
                  // Get the assignees of the issue
                  const assignees = await github.rest.issues.listAssignees({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number
                  });
                  // Create a comma-separated list of assignees' usernames
                  const assigneeUsernames = assignees.data.map(assignee => assignee.login);
                  mentionText = `@${assigneeUsernames.join(', @')}`;
                }

                // Create a comment text to be posted on the issue
                const commentText = `Hey ${mentionText}, ${inputs.comment}`;
                console.log('Comment text:', commentText);

                // Post a comment on the issue
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: commentText
                });
              }
            }

            console.log('Step 4: Workflow completed');
