name: check release
on:
  workflow_call:
    inputs:
      release:
        description: 'Number of days for considering an issue outdated'
        required: true
        type: string

jobs:
  check-release:
    name: Release Prefix
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Value
        run: echo "Release value is:${{ inputs.release }}"
        id: release_prefix
      - id: step1
        run: echo "prefix" >> $GITHUB_OUTPUT
    outputs:
      prefix: ${{ steps.release_prefix.outputs.prefix }}
