name: check release
on:
  workflow_call:

jobs:
 check-release:
  name: Release Prefix
  runs-on: ubuntu-latest
  steps:
    - name: Print Release Value
      run: echo "Release value is: ${{ inputs.release }}"
