name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        description: 'Deployment environment'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setting up deployment file
      env:
        REPOSITORY: ${{ github.event.repository.ssh_url }}
        KEY: ${{ secrets.KEY }}
       
      run: |
        echo "Repository URL: $REPOSITORY"
        echo "KEY: $KEY"

  
    
