name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        description: 'Deployment environment'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: self-hosted

    env:
      REPOSITORY: ${{ github.event.repository.ssh_url }}
      KEY: ${{ secrets.KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print environment variables
      run: |
        echo "Repository URL: $REPOSITORY"
        echo "KEY: $KEY"
        printenv KEY
