name: check release
on:
  workflow_call:

jobs:
  check-release:
    name: Release Prefix
    runs-on: ubuntu-latest
    #     This is to know if the reference of the trigger i.e the tag is a release or prerelease. Later to avoid any release which are not created or in Draft state.
    steps:
    - uses: actions/checkout@v4
    - name: Check the release details
      id: release_prefix
      run: |
        gh release view ${{ inputs.release }} --json isPrerelease,isDraft --jq 'if .isPrerelease==false and .isDraft==false then "release" elif .isPrerelease==true and .isDraft==false then "prerelease" else "draft" end' >> release-prefix.json
        echo "prefix=`cat release-prefix.json`" >> $GITHUB_OUTPUT
    outputs:
      prefix: ${{ steps.release_prefix.outputs.prefix }}
