name: History Check

on:
  workflow_call:

jobs:

  check-history:
    name: Check if release is behind
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Compare history
      id: history
      run: |
        git checkout main
        TAG_META=$( git tag ${{ github.event.release.tag_name }} --contains main )
        echo "Release Tag Name: ${{ github.event.release.tag_name }}"
        echo "${TAG_META}"
        if [ "${TAG_META}"=="${{ github.event.release.tag_name }}" ]; then
          echo "clean"
          echo "clean=true" >> $GITHUB_OUTPUT
        else
          echo "Not clean"
          echo "clean=false" >> $GITHUB_OUTPUT
        fi
    outputs:
      clean: ${{ steps.history.outputs.clean }}
