name: Redmine COmment
on:
  workflow_call:
   inputs:
     deployment_status:
       description: 'Deployment status'
       required: true
       type: string
     
jobs:
  redmine_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Check Deployment Status
      run: |
        echo "Deployment status from previous job: ${{ needs.deployment.outputs.deployment_status }}"

    - name: Send Redmine Comment
      env:
        REDMINE_ISSUE_ID: ${{ github.event.inputs.redmine_issue_id }}
        REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
        DEPLOYMENT_STATUS: ${{ inputs.deployment_status }}
        DEPLOY_ENVIRONMENT: ${{ github.event.inputs.deploy_environment }}
        COMMIT_ID: ${{ github.sha }}
        WORKFLOW_LOGS_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      run: |
        echo "Sending deployment status to Redmine..."
        echo "DEPLOYMENT_STATUS: ${DEPLOYMENT_STATUS}"  # Debugging step
        echo "COMMIT_ID: ${COMMIT_ID}"
        echo "WORKFLOW_LOGS_URL: ${WORKFLOW_LOGS_URL}"

        curl -X PUT "https://redmine.yapsody.net/issues/${REDMINE_ISSUE_ID}.json" \
        -H "Content-Type: application/json" \
        -H "X-Redmine-API-Key: ${REDMINE_API_KEY}" \
        -d "{
          \"issue\": {
            \"notes\": \"Deployment Status: ${DEPLOYMENT_STATUS}\nEnvironment: ${DEPLOY_ENVIRONMENT}\nCommit ID: ${COMMIT_ID}\nWorkflow Logs: ${WORKFLOW_LOGS_URL}\"
          }
        }"
