name: Redmine Comment

on:
  workflow_call:
    inputs:
      redmine_issue_id:
        description: "Redmine Issue ID"
        required: true
        type: string
      deployment_note:
        description: "Redmine deployment note"
        required: true
        type: string

jobs:
  redmine_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Check Deployment Note
      run: |
        echo "Deployment Note from previous job: ${{ inputs.deployment_note }}"

    - name: Send Redmine Comment
      env:
        REDMINE_ISSUE_ID: ${{ inputs.redmine_issue_id }}
        REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
        DEPLOYMENT_NOTE: ${{ inputs.deployment_note }}
      run: |
        echo "Sending deployment note to Redmine..."
        echo "DEPLOYMENT_NOTE: ${DEPLOYMENT_NOTE}"  

        curl -X PUT "https://redmine.yapsody.net/issues/${REDMINE_ISSUE_ID}.json" \
        -H "Content-Type: application/json" \
        -H "X-Redmine-API-Key: ${REDMINE_API_KEY}" \
        -d "{
          \"issue\": {
            \"notes\": \"${DEPLOYMENT_NOTE}\"
          }
        }"
